__all__ = ["control_router", "reporte_router"]

from fastapi import APIRouter

from .control_aporte_empresario import control_aporte_empresario_router
from .control_banco import control_banco_router
from .control_completo import control_completo_router
from .control_debitos_bancarios import control_debitos_bancarios_router
from .control_deuda_flotante import control_deuda_flotante_router
from .control_escribanos import control_escribanos_router
from .control_haberes import control_haberes_router
from .control_honorarios import control_honorarios_router
from .control_icaro_vs_siif import control_icaro_vs_siif_router
from .control_obras import control_obras_router
from .control_recursos import control_recursos_router
from .control_viaticos import control_viaticos_router
from .reporte_ejecucion_obras import reporte_ejecucion_obras_router
from .reporte_formulacion_presupuesto import reporte_formulacion_presupuesto_router
from .reporte_libro_diario import reporte_libro_diario_router
from .reporte_modulos_basicos import reporte_modulos_basicos_router
from .reporte_planillometro import reporte_planillometro_router
from .reporte_planillometro_contabilidad import (
    reporte_planillometro_contabilidad_router,
)

control_router = APIRouter(prefix="/control", tags=["Controles"])
control_router.include_router(control_completo_router)
control_router.include_router(control_recursos_router)
control_router.include_router(control_aporte_empresario_router)
control_router.include_router(control_icaro_vs_siif_router)
control_router.include_router(control_obras_router)
control_router.include_router(control_haberes_router)
control_router.include_router(control_honorarios_router)
control_router.include_router(control_escribanos_router)
control_router.include_router(control_viaticos_router)
control_router.include_router(control_debitos_bancarios_router)
control_router.include_router(control_banco_router)
control_router.include_router(control_deuda_flotante_router)

reporte_router = APIRouter(prefix="/reporte", tags=["Reportes"])
reporte_router.include_router(reporte_formulacion_presupuesto_router)
reporte_router.include_router(reporte_planillometro_router)
reporte_router.include_router(reporte_modulos_basicos_router)
reporte_router.include_router(reporte_libro_diario_router)
reporte_router.include_router(reporte_planillometro_contabilidad_router)
reporte_router.include_router(reporte_ejecucion_obras_router)
